# Generated by Django 4.2.16 on 2024-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='path/to/my/default/image.jpg', null=True, upload_to=''),
        ),
    ]
